### ISSUE TITLE
Install issues finding modules

### ISSUE THREAD

**Issue by quisquous** [arcan1s/ffxivbis#1]
I see that setup grabs everything into .eggs, but when I run `python -m service.application.application` it can't find them.  Do I need to adjust PYTHONPATH somehow?

Error is: `ModuleNotFoundError: No module named 'aiohttp_jinja2'`

**Comment by arcan1s** [comment]
I've added notes about using venv and a bit updated configuration, thus something like:

```
virtualenv -p python3.7 env
source env/bin/activate
python setup.py install
pip install aiosqlite
python -m ffxivbis.application.application -c package/ini/ffxivbis.ini 
```

should work now. Note though that you still will need to make some changes in configuration, at least `web.templates` has to be amended to fullpath to `template` directory
